main: com.rooxchicken.orbit.Orbit
name: OrbitPlugin
version: 0.1
api-version: '1.20'

commands:
   setorbit:
      description: Sets the user's orbit to the specified number
      usage: /setorbit <orbit>
   resetcooldown:
      description: Resets the cooldown
      usage: /resetcooldown

depend: [ ProtocolLib ]